import { useEffect, useState } from 'react';

/**
 * Lightweight hook that registers the Workbox service-worker generated by
 * vite-plugin-pwa and exposes an "update available" flag so the UI can
 * prompt the user to refresh.
 */
export function usePwaRegistration() {
  const [needRefresh, setNeedRefresh] = useState(false);
  const [registration, setRegistration] = useState<ServiceWorkerRegistration | null>(null);

  useEffect(() => {
    if (!('serviceWorker' in navigator)) return;

    const register = async () => {
      try {
        const { registerSW } = await import('virtual:pwa-register');
        const updateSW = registerSW({
          immediate: false,
          onRegisteredSW(_swUrl: string, reg: ServiceWorkerRegistration | undefined) {
            if (reg) setRegistration(reg);
          },
          onNeedRefresh() {
            setNeedRefresh(true);
          },
        });

        // Store updateSW so we can call it from acceptUpdate
        (window as unknown as Record<string, unknown>).__pwaUpdateSW = updateSW;
      } catch {
        // SW registration failed (e.g. non-HTTPS in dev) — silently ignore
      }
    };

    register();
  }, []);

  const acceptUpdate = () => {
    const updateSW = (window as unknown as Record<string, unknown>).__pwaUpdateSW as
      | ((reloadPage?: boolean) => Promise<void>)
      | undefined;
    if (updateSW) {
      updateSW(true);
    }
    setNeedRefresh(false);
  };

  const dismissUpdate = () => setNeedRefresh(false);

  return { needRefresh, acceptUpdate, dismissUpdate, registration };
}
