version = 5.4.0
archive_dir = /etc/letsencrypt/archive/dociva.io
cert = /etc/letsencrypt/live/dociva.io/cert.pem
privkey = /etc/letsencrypt/live/dociva.io/privkey.pem
chain = /etc/letsencrypt/live/dociva.io/chain.pem
fullchain = /etc/letsencrypt/live/dociva.io/fullchain.pem
[renewalparams]
account = 3bd6e7cb34e5ccc0d7d8a6ae4319115e
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
webroot_path = /var/www/certbot,
[[webroot_map]]
dociva.io = /var/www/certbot
www.dociva.io = /var/www/certbot
