version = 5.4.0
archive_dir = /etc/letsencrypt/archive/git.dociva.io
cert = /etc/letsencrypt/live/git.dociva.io/cert.pem
privkey = /etc/letsencrypt/live/git.dociva.io/privkey.pem
chain = /etc/letsencrypt/live/git.dociva.io/chain.pem
fullchain = /etc/letsencrypt/live/git.dociva.io/fullchain.pem
[renewalparams]
account = 3bd6e7cb34e5ccc0d7d8a6ae4319115e
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
git.dociva.io = /var/www/certbot
