#!/bin/bash
# =============================================================================
# server-setup.sh — One-time setup for the production server
# Run once after cloning the repo: bash scripts/server-setup.sh
# =============================================================================
set -euo pipefail

echo "=============================="
echo " Dociva — Server First-Time Setup"
echo "=============================="

cd ~/SaaS-PDF

# ── 1. Validate redis.conf has correct bind ──────────────────────────────────
if grep -q "^bind 127\.0\.0\.1" deploy/redis/redis.conf; then
    echo "⚠️  Fixing redis.conf: bind 127.0.0.1 → bind 0.0.0.0"
    sed -i 's/^bind 127\.0\.0\.1.*/bind 0.0.0.0/' deploy/redis/redis.conf
fi
echo "✅ redis.conf bind: OK"

# ── 2. Extract Redis password from redis.conf ────────────────────────────────
REDIS_PASS=$(grep "^requirepass" deploy/redis/redis.conf 2>/dev/null | awk '{print $2}' || echo "")

if [ -z "$REDIS_PASS" ]; then
    echo "ℹ️  No requirepass in redis.conf — using password-less Redis URL"
    REDIS_BASE_URL="redis://redis:6379"
else
    echo "✅ Redis password found in redis.conf"
    REDIS_BASE_URL="redis://:${REDIS_PASS}@redis:6379"
fi

# ── 3. Generate or preserve SECRET_KEY ──────────────────────────────────────
if [ -f /root/server-secrets.env ] && grep -q "^SECRET_KEY=" /root/server-secrets.env; then
    SECRET_KEY=$(grep "^SECRET_KEY=" /root/server-secrets.env | cut -d= -f2-)
    echo "✅ SECRET_KEY already exists — keeping it"
else
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    echo "✅ Generated new SECRET_KEY"
fi

# ── 4. Create /root/server-secrets.env ──────────────────────────────────────
cat > /root/server-secrets.env << EOF
# ════════════════════════════════════════════════════
# Dociva — Production Secrets
# DO NOT commit this file to Git
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# ════════════════════════════════════════════════════

SECRET_KEY=${SECRET_KEY}

REDIS_URL=${REDIS_BASE_URL}/0
CELERY_BROKER_URL=${REDIS_BASE_URL}/0
CELERY_RESULT_BACKEND=${REDIS_BASE_URL}/1

# Rate limiter — uses Redis when available, memory:// otherwise
RATELIMIT_STORAGE_URI=${REDIS_BASE_URL}/2

FLASK_ENV=production
EOF

chmod 600 /root/server-secrets.env
echo "✅ /root/server-secrets.env created"

# ── 5. Create docker-compose.override.yml ───────────────────────────────────
cat > ~/SaaS-PDF/docker-compose.override.yml << 'OVERRIDE_EOF'
# ════════════════════════════════════════════════════
# docker-compose.override.yml — Production overrides
# Auto-generated by scripts/server-setup.sh
# This file is gitignored — safe to store secrets here
# ════════════════════════════════════════════════════
services:
  backend:
    env_file:
      - /root/server-secrets.env
    environment:
      - FLASK_ENV=production

  celery_worker:
    env_file:
      - /root/server-secrets.env

  celery_beat:
    env_file:
      - /root/server-secrets.env
OVERRIDE_EOF

echo "✅ docker-compose.override.yml created"

# ── 6. Validate setup ────────────────────────────────────────────────────────
echo ""
echo "════ Validation ════"
echo "redis.conf bind:"
grep "^bind" deploy/redis/redis.conf

echo "server-secrets.env content:"
grep -E "^(REDIS_URL|CELERY_BROKER|SECRET_KEY|FLASK_ENV)" /root/server-secrets.env

echo ""
echo "✅ Setup complete! You can now run: ~/deploy.sh"
echo "═══════════════════════════════════════════════"
